services:
  app:
    image: ghcr.io/dgolzman/basketallboys:main
    container_name: basket-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - AUTH_URL=${AUTH_URL:-http://localhost:3000}
